apiVersion: apps/v1
kind: Deployment
metadata:
  name: omicidx-fastapi
  labels:
    app: omicidx-fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: omicidx-fastapi
  template:
    metadata:
      labels:
        app: omicidx-fastapi
    spec:
      containers:
      - name: omicidx-fastapi
        image: gcr.io/isb-cgc-01-0006/omicidx-fastapi
        ports:
        - containerPort: 80
